version: '3.8'

services:
  codellama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

  flask-server:
    build: .
    volumes:
      - .:/app
    ports:
      - "11435:11434"
    depends_on:
      - codellama

volumes:
  ollama:
